#!/usr/bin/env python3
"""
Generate MkDocs pages listing bundled TRSE library units (.tru) under units/.

Source of truth (TRSE repository root):
  - units/<SYSTEM>/.../*.tru   — platform-specific and shared libraries
  - units/global/...             — always on the search path after CPU-specific
  - units/cpu_specific/<CPU>/... — CPU-specific (6502, Z80, 6809, …)

Usage (from repo root or retrodocs/):
  python3 retrodocs/scripts/import_trse_units.py
  python3 retrodocs/scripts/import_trse_units.py --repo-root /path/to/TRSE

Then: mkdocs build
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path


BANNER = "<!-- AUTO-GENERATED by retrodocs/scripts/import_trse_units.py — do not edit -->\n"


def find_repo_root(start: Path) -> Path:
    here = start.resolve()
    for p in [here] + list(here.parents):
        if (p / "units").is_dir() and (p / "resources").is_dir():
            return p
    raise FileNotFoundError(
        "Could not find TRSE root (expected units/ and resources/). "
        "Pass --repo-root /path/to/TRSE"
    )


def rel_tru_paths(root: Path, base: Path) -> list[str]:
    out: list[str] = []
    for f in sorted(base.rglob("*.tru")):
        rel = f.relative_to(base).as_posix()
        if rel.endswith(".tru"):
            rel = rel[: -len(".tru")]
        out.append(rel)
    return out


def slug_for_folder(name: str) -> str:
    return name.lower().replace(" ", "_")


def write_system_page(
    out_units: Path,
    folder_name: str,
    rel_paths: list[str],
) -> None:
    slug = slug_for_folder(folder_name)
    path = out_units / f"{slug}.md"
    title = f"TRSE units: {folder_name}"
    meta = (
        "---\n"
        f'title: "{title}"\n'
        "description: Bundled Turbo Rascal unit files (.tru) shipped with TRSE\n"
        "---\n\n"
    )
    body = [BANNER, meta, f"# {folder_name}\n\n"]
    body.append(
        f"These paths are relative to `units/{folder_name}/` in the TRSE tree. "
        f"Reference a unit with `@use \"<path>\"` (no `.tru` extension).\n\n"
    )
    if not rel_paths:
        body.append("*No `.tru` files in this folder.*\n")
    else:
        body.append("## Files\n\n")
        for p in rel_paths:
            body.append(f"- `{p}`\n")
    path.write_text("".join(body), encoding="utf-8")


def write_cpu_specific_page(out_units: Path, cpu_root: Path) -> None:
    """One page with a section per immediate CPU subfolder."""
    path = out_units / "cpu_specific.md"
    sections: list[str] = []
    cpus = sorted(
        d for d in cpu_root.iterdir() if d.is_dir() and not d.name.startswith(".")
    )
    for cpu_dir in cpus:
        rels = rel_tru_paths(cpu_root, cpu_dir)
        sections.append(f"## `{cpu_dir.name}`\n\n")
        if not rels:
            sections.append("*No `.tru` files.*\n\n")
            continue
        for p in rels:
            rel_full = f"{cpu_dir.name}/{p}"
            sections.append(f"- `{rel_full}`\n")
        sections.append("\n")
    meta = (
        "---\n"
        'title: "TRSE units: cpu_specific"\n'
        "description: CPU-specific Turbo Rascal units (6502, Z80, …)\n"
        "---\n\n"
    )
    intro = (
        f"{BANNER}{meta}"
        "# cpu_specific\n\n"
        "These units live under `units/cpu_specific/<CPU>/`. "
        "TRSE resolves `@use` after system units and before `units/global/`.\n\n"
        "Paths below are relative to `units/cpu_specific/` "
        "(include the CPU folder in the `@use` string).\n\n"
    )
    path.write_text(intro + "".join(sections), encoding="utf-8")


def write_index(
    out_index: Path,
    rows: list[tuple[str, int, str]],
    n_total: int,
    n_systems: int,
) -> None:
    lines = [
        BANNER,
        "---\n",
        'title: "Included TRSE units"\n',
        "description: Catalog of bundled .tru library files per platform\n",
        "---\n\n",
        "# Included TRSE units\n\n",
        "TRSE ships **Turbo Rascal unit** files (`.tru`) under the `units/` directory "
        "in the source tree. They provide graphics helpers, drivers, music players, "
        "and other shared code you can pull into a project with the **`@use`** directive.\n\n",
        "## How `@use` is resolved\n\n",
        "When the compiler sees `@use \"some/path/name\"`, it searches for "
        "`some/path/name.tru` in this order ([`parser.cpp`](https://github.com/leuat/TRSE/blob/master/source/Compiler/parser.cpp)):\n\n",
        "1. **Project directory** (where your main `.ras` file lives)\n",
        "2. **`units/<SYSTEM>/`** — your project's `system = ...` target "
        "(folder name matches the system, e.g. `C64`, `VIC20`, `TRS80COCO`)\n",
        "3. **`units/cpu_specific/<CPU>/`** — CPU for the current target "
        "(e.g. `MOS6502`, `Z80`, `M6809`). The special case **Z180** uses the **Z80** folder.\n",
        "4. **`units/global/`** — shared across platforms\n\n",
        "Place your own reusable `.tru` files in the project folder, or rely on these "
        "bundled libraries. The lists below reflect the **upstream TRSE repository** "
        "at doc generation time.\n\n",
        f"**Totals:** {n_total} `.tru` files across {n_systems} top-level folders "
        "(including `global` and `cpu_specific`).\n\n",
        "## Catalog by platform folder\n\n",
        "| Folder | Units | |\n",
        "|--------|------:|---|\n",
    ]
    for folder, count, slug in rows:
        lines.append(f"| `{folder}` | {count} | [View list](units/{slug}.md) |\n")
    lines.append(
        "\n---\n\n"
        "*Regenerate this page and the per-folder lists with:* "
        "`python3 retrodocs/scripts/import_trse_units.py` "
        "(run from the TRSE repo root; `deploy.sh` runs it automatically.)\n"
    )
    out_index.write_text("".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate TRSE units catalog for MkDocs.")
    ap.add_argument(
        "--repo-root",
        type=Path,
        help="TRSE repository root (default: auto-detect from script location)",
    )
    args = ap.parse_args()
    script = Path(__file__).resolve()
    repo = args.repo_root.resolve() if args.repo_root else find_repo_root(script.parent)
    units_dir = repo / "units"
    if not units_dir.is_dir():
        print(f"Error: missing {units_dir}", file=sys.stderr)
        return 1

    retrodocs_docs = repo / "retrodocs" / "docs"
    out_index = retrodocs_docs / "trse" / "reference" / "units-index.md"
    out_units = retrodocs_docs / "trse" / "reference" / "units"
    out_units.mkdir(parents=True, exist_ok=True)

    rows: list[tuple[str, int, str]] = []
    n_total = 0

    # Top-level folders under units/
    children = sorted(
        p for p in units_dir.iterdir() if p.is_dir() and not p.name.startswith(".")
    )

    for child in children:
        name = child.name
        if name == "cpu_specific":
            rels = rel_tru_paths(units_dir, child)
            n_total += len(rels)
            rows.append((name, len(rels), "cpu_specific"))
            write_cpu_specific_page(out_units, child)
            continue

        rels = rel_tru_paths(units_dir, child)
        n_total += len(rels)
        slug = slug_for_folder(name)
        rows.append((name, len(rels), slug))
        write_system_page(out_units, name, rels)

    write_index(out_index, rows, n_total, len(rows))
    print(f"Wrote {out_index} and {len(rows)} unit listing(s) under {out_units}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
