#!/usr/bin/env python3
"""
Generate MkDocs pages under docs/trse/reference/ from TRSE IDE help sources.

Source of truth (in TRSE repository root):
  - resources/text/syntax.txt   — index (m/r/c/p/f lines)
  - resources/text/help/<t>/<name>.rtf — HTML body (despite .rtf extension)

Usage (from repo root or retrodocs/):
  python3 retrodocs/scripts/import_trse_reference.py
  python3 retrodocs/scripts/import_trse_reference.py --repo-root /path/to/TRSE

Then: mkdocs build

Options:
  --types m,r,c   Comma-separated row types (default: m)
  --skip-init     Skip methods whose names start with "init" (matches IDE help list)
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


BANNER = "<!-- AUTO-GENERATED by retrodocs/scripts/import_trse_reference.py — do not edit -->\n"


def find_repo_root(start: Path) -> Path:
    """Walk up from script location to find TRSE root (directory containing resources/text/syntax.txt)."""
    here = start.resolve()
    for p in [here] + list(here.parents):
        if (p / "resources" / "text" / "syntax.txt").is_file():
            return p
    raise FileNotFoundError(
        "Could not find resources/text/syntax.txt. Pass --repo-root /path/to/TRSE"
    )


def slug_for_method(name: str, systems: str, used: dict[str, int]) -> str:
    """Stable filename: lowercase name; append -2, -3 on duplicates."""
    base = re.sub(r"[^a-z0-9_]+", "_", name.strip().lower()).strip("_") or "method"
    used[base] = used.get(base, 0) + 1
    n = used[base]
    if n == 1:
        return base
    return f"{base}-{n}"


def load_help_body(repo: Path, kind: str, word: str) -> str | None:
    """Load HTML fragment; kind is m/r/c/p single letter."""
    sub = kind.lower()
    w = word.strip().lower()
    path = repo / "resources" / "text" / "help" / sub / f"{w}.rtf"
    if not path.is_file():
        return None
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError as e:
        return f"<p><em>Could not read help file: {e}</em></p>"


def esc_md(s: str) -> str:
    return s.replace("\\", "\\\\").replace("|", "\\|")


def write_method_page(
    out_dir: Path,
    slug: str,
    name: str,
    systems: str,
    params: str,
    html: str | None,
) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{slug}.md"
    meta = f'---\ntitle: "{name}"\ndescription: TRSE built-in method (from IDE help)\n---\n\n'
    sig = f"**Systems:** {esc_md(systems) if systems else '—'}  \n**Parameters:** `{esc_md(params) if params else '—'}`\n\n---\n\n"
    body = ""
    if html:
        body = f'<div markdown="0" class="trse-help-body">\n\n{html}\n\n</div>\n'
    else:
        body = (
            "*No help file found in the repository for this method.* "
            "(Expected `resources/text/help/m/{}.rtf`.)\n".format(name.lower())
        )
    path.write_text(BANNER + meta + f"# `{name}`\n\n" + sig + body, encoding="utf-8")


def parse_methods(lines: list[str], skip_init: bool) -> list[dict]:
    rows: list[dict] = []
    for line in lines:
        raw = line.strip()
        if not raw or raw.startswith("#"):
            continue
        parts = [p.strip() for p in raw.split(";")]
        if len(parts) < 3:
            continue
        if parts[0].lower() != "m":
            continue
        name = parts[1]
        if not name:
            continue
        if skip_init and name.lower().startswith("init"):
            continue
        systems = parts[2] if len(parts) > 2 else ""
        params = parts[3] if len(parts) > 3 else ""
        rows.append({"name": name, "systems": systems, "params": params})
    return rows


def write_methods_index(
    out_path: Path,
    items: list[tuple[str, str, str, str]],
) -> None:
    """items: (slug, name, systems, params)"""
    lines = [
        "---",
        'title: "TRSE methods (reference)"',
        "description: Built-in methods from TRSE syntax.txt + IDE help files",
        "---",
        "",
        BANNER.strip(),
        "",
        "# TRSE methods (reference)",
        "",
        "Generated from `resources/text/syntax.txt` and `resources/text/help/m/*.rtf` in the TRSE repository.",
        "",
        "| Method | Systems (excerpt) | Parameters |",
        "|--------|-------------------|------------|",
    ]
    for slug, name, systems, params in sorted(items, key=lambda x: x[1].lower()):
        sys_short = (systems[:48] + "…") if len(systems) > 50 else systems
        lines.append(
            f"| [`{name}`](methods/{slug}.md) | {esc_md(sys_short)} | `{esc_md(params)}` |"
        )
    lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="Import TRSE IDE help into retrodocs")
    ap.add_argument(
        "--repo-root",
        type=Path,
        default=None,
        help="TRSE repository root (contains resources/text/)",
    )
    ap.add_argument(
        "--skip-init",
        action="store_true",
        help="Skip methods starting with init (like the IDE help list)",
    )
    args = ap.parse_args()

    script_dir = Path(__file__).resolve().parent
    retrodocs = script_dir.parent
    docs_dir = retrodocs / "docs"

    try:
        repo = args.repo_root.resolve() if args.repo_root else find_repo_root(script_dir)
    except FileNotFoundError as e:
        print(e, file=sys.stderr)
        return 1

    syntax_file = repo / "resources" / "text" / "syntax.txt"
    lines = syntax_file.read_text(encoding="utf-8", errors="replace").splitlines()

    methods = parse_methods(lines, skip_init=args.skip_init)
    out_methods = docs_dir / "trse" / "reference" / "methods"
    used_slugs: dict[str, int] = {}

    index_items: list[tuple[str, str, str, str]] = []
    missing = 0
    for m in methods:
        name = m["name"]
        systems = m["systems"]
        params = m["params"]
        slug = slug_for_method(name, systems, used_slugs)
        html = load_help_body(repo, "m", name)
        if html is None:
            missing += 1
        write_method_page(out_methods, slug, name, systems, params, html)
        index_items.append((slug, name, systems, params))

    idx_path = docs_dir / "trse" / "reference" / "methods-index.md"
    write_methods_index(idx_path, index_items)

    print(f"Repository: {repo}")
    print(f"Methods written: {len(methods)} → {out_methods}")
    print(f"Index: {idx_path}")
    print(f"Help files missing: {missing} (pages still created with stub)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
