#!/usr/bin/env python3
"""
Generate MkDocs pages listing bundled TRSE library units (.tru) under units/,
including procedure/function signatures and preceding block comments.

Source of truth (TRSE repository root):
  - units/<SYSTEM>/.../*.tru   — platform-specific and shared libraries
  - units/global/...             — always on the search path after CPU-specific
  - units/cpu_specific/<CPU>/... — CPU-specific (6502, Z80, 6809, …)

Usage (from repo root or retrodocs/):
  python3 retrodocs/scripts/import_trse_units.py
  python3 retrodocs/scripts/import_trse_units.py --repo-root /path/to/TRSE

Then: mkdocs build
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Allow `from tru_extract import ...` when run as script
_SCRIPTS = Path(__file__).resolve().parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from tru_extract import Decl, doc_to_markdown, extract_decls  # noqa: E402


BANNER = "<!-- AUTO-GENERATED by retrodocs/scripts/import_trse_units.py — do not edit -->\n"


def find_repo_root(start: Path) -> Path:
    here = start.resolve()
    for p in [here] + list(here.parents):
        if (p / "units").is_dir() and (p / "resources").is_dir():
            return p
    raise FileNotFoundError(
        "Could not find TRSE root (expected units/ and resources/). "
        "Pass --repo-root /path/to/TRSE"
    )


def rel_tru_paths(root: Path, base: Path) -> list[str]:
    out: list[str] = []
    for f in sorted(base.rglob("*.tru")):
        rel = f.relative_to(base).as_posix()
        if rel.endswith(".tru"):
            rel = rel[: -len(".tru")]
        out.append(rel)
    return out


def slug_for_folder(name: str) -> str:
    return name.lower().replace(" ", "_")


def esc_cell(s: str) -> str:
    """Escape pipes for markdown table cells."""
    return s.replace("|", "\\|")


def format_tru_file_section(
    base_dir: Path, rel_no_ext: str, display_path: str | None = None
) -> str:
    """Markdown section for one .tru file: heading + optional table of decls."""
    tru_path = base_dir / f"{rel_no_ext}.tru"
    heading = display_path if display_path is not None else rel_no_ext
    try:
        raw = tru_path.read_text(encoding="utf-8", errors="replace")
    except OSError as e:
        return f"### `{heading}`\n\n*Could not read file: {e}*\n\n"

    decls = extract_decls(raw)
    lines: list[str] = [f"### `{heading}`\n\n"]

    if not decls:
        lines.append(
            "*No `procedure` / `function` declarations found "
            "(unit may use only `@include`, variables, or declarations this parser skips).*\n\n"
        )
        return "".join(lines)

    lines.append("| Kind | Name | Signature | Notes |\n")
    lines.append("|------|------|-----------|-------|\n")
    for d in decls:
        notes = doc_to_markdown(d.doc) if d.doc else "—"
        lines.append(
            f"| `{d.kind}` | `{esc_cell(d.name)}` | `{esc_cell(d.signature)}` | {notes} |\n"
        )
    lines.append("\n")
    return "".join(lines)


def write_folder_page(
    out_units: Path,
    folder_title: str,
    base_dir: Path,
    rel_paths: list[str],
    intro_extra: str,
) -> None:
    slug = slug_for_folder(folder_title)
    path = out_units / f"{slug}.md"
    # No YAML front matter: MkDocs does not strip --- blocks; they render as visible text.
    body: list[str] = [BANNER, f"# {folder_title}\n\n", intro_extra]
    if not rel_paths:
        body.append("*No `.tru` files in this folder.*\n")
        path.write_text("".join(body), encoding="utf-8")
        return

    body.append("## Units\n\n")
    body.append(
        "Each section lists **`procedure` and `function` declarations** parsed from the "
        "`.tru` source. **Notes** come from the **block comment** immediately above each "
        "declaration (`/** … */` or `/* … */`). Line comments (`//`) are not shown.\n\n"
    )
    for rel in rel_paths:
        body.append(format_tru_file_section(base_dir, rel))

    path.write_text("".join(body), encoding="utf-8")


def write_cpu_specific_page(out_units: Path, cpu_root: Path) -> None:
    path = out_units / "cpu_specific.md"
    body: list[str] = [
        BANNER,
        "# cpu_specific\n\n",
        "These units live under `units/cpu_specific/<CPU>/`. "
        "TRSE resolves `@use` after system units and before `units/global/`.\n\n"
        "Paths in headings are relative to `units/cpu_specific/<CPU>/`.\n\n",
        "## Units\n\n",
        "Each section lists **`procedure` and `function` declarations** parsed from the "
        "`.tru` source. **Notes** come from block comments above each declaration.\n\n",
    ]
    cpus = sorted(
        d for d in cpu_root.iterdir() if d.is_dir() and not d.name.startswith(".")
    )
    for cpu_dir in cpus:
        rels = rel_tru_paths(cpu_root, cpu_dir)
        body.append(f"## `{cpu_dir.name}`\n\n")
        if not rels:
            body.append("*No `.tru` files.*\n\n")
            continue
        for rel in rels:
            display = f"{cpu_dir.name}/{rel}"
            body.append(format_tru_file_section(cpu_dir, rel, display_path=display))
    path.write_text("".join(body), encoding="utf-8")


def write_index(
    out_index: Path,
    rows: list[tuple[str, int, str]],
    n_total: int,
    n_systems: int,
) -> None:
    lines = [
        BANNER,
        "# Included TRSE units\n\n",
        "TRSE ships **Turbo Rascal unit** files (`.tru`) under the `units/` directory "
        "in the source tree. They provide graphics helpers, drivers, music players, "
        "and other shared code you can pull into a project with the **`@use`** directive.\n\n",
        "Platform pages list each unit file with **procedure/function signatures** and "
        "**block-comment notes** extracted from the source (auto-generated; edge cases may be missing).\n\n",
        "## How `@use` is resolved\n\n",
        "When the compiler sees `@use \"some/path/name\"`, it searches for "
        "`some/path/name.tru` in this order ([`parser.cpp`](https://github.com/leuat/TRSE/blob/master/source/Compiler/parser.cpp)):\n\n",
        "1. **Project directory** (where your main `.ras` file lives)\n",
        "2. **`units/<SYSTEM>/`** — your project's `system = ...` target "
        "(folder name matches the system, e.g. `C64`, `VIC20`, `TRS80COCO`)\n",
        "3. **`units/cpu_specific/<CPU>/`** — CPU for the current target "
        "(e.g. `MOS6502`, `Z80`, `M6809`). The special case **Z180** uses the **Z80** folder.\n",
        "4. **`units/global/`** — shared across platforms\n\n",
        "Place your own reusable `.tru` files in the project folder, or rely on these "
        "bundled libraries. The lists below reflect the **upstream TRSE repository** "
        "at doc generation time.\n\n",
        f"**Totals:** {n_total} `.tru` files across {n_systems} top-level folders "
        "(including `global` and `cpu_specific`).\n\n",
        "## Catalog by platform folder\n\n",
        "| Folder | Units | |\n",
        "|--------|------:|---|\n",
    ]
    for folder, count, slug in rows:
        lines.append(f"| `{folder}` | {count} | [View list](units/{slug}.md) |\n")
    lines.append(
        "\n---\n\n"
        "*Regenerate this page and the per-folder lists with:* "
        "`python3 retrodocs/scripts/import_trse_units.py` "
        "(run from the TRSE repo root; `deploy.sh` runs it automatically.)\n"
    )
    out_index.write_text("".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate TRSE units catalog for MkDocs.")
    ap.add_argument(
        "--repo-root",
        type=Path,
        help="TRSE repository root (default: auto-detect from script location)",
    )
    args = ap.parse_args()
    script = Path(__file__).resolve()
    repo = args.repo_root.resolve() if args.repo_root else find_repo_root(script.parent)
    units_dir = repo / "units"
    if not units_dir.is_dir():
        print(f"Error: missing {units_dir}", file=sys.stderr)
        return 1

    retrodocs_docs = repo / "retrodocs" / "docs"
    out_index = retrodocs_docs / "trse" / "reference" / "units-index.md"
    out_units = retrodocs_docs / "trse" / "reference" / "units"
    out_units.mkdir(parents=True, exist_ok=True)

    rows: list[tuple[str, int, str]] = []
    n_total = 0

    children = sorted(
        p for p in units_dir.iterdir() if p.is_dir() and not p.name.startswith(".")
    )

    for child in children:
        name = child.name
        if name == "cpu_specific":
            rels = rel_tru_paths(units_dir, child)
            n_total += len(rels)
            rows.append((name, len(rels), "cpu_specific"))
            write_cpu_specific_page(out_units, child)
            continue

        rels = rel_tru_paths(units_dir, child)
        n_total += len(rels)
        slug = slug_for_folder(name)
        rows.append((name, len(rels), slug))
        intro = (
            f"These paths are relative to `units/{name}/` in the TRSE tree. "
            f"Reference a unit with `@use \"<path>\"` (no `.tru` extension).\n\n"
        )
        write_folder_page(out_units, name, child, rels, intro)

    write_index(out_index, rows, n_total, len(rows))
    print(f"Wrote {out_index} and {len(rows)} unit listing(s) under {out_units}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
